CREATE TABLE mainnet.int_custody_probe_order_by_slot
(
    `updated_date_time` DateTime COMMENT 'Timestamp when the record was last updated' CODEC(DoubleDelta, ZSTD(1)),
    `probe_date_time` DateTime COMMENT 'Earliest event time for this probe batch' CODEC(DoubleDelta, ZSTD(1)),
    `slot` UInt32 COMMENT 'Slot number' CODEC(DoubleDelta, ZSTD(1)),
    `slot_start_date_time` DateTime COMMENT 'Start date time of the slot' CODEC(DoubleDelta, ZSTD(1)),
    `peer_id_unique_key` Int64 COMMENT 'Unique key associated with the identifier of the peer' CODEC(ZSTD(1)),
    `result` LowCardinality(String) COMMENT 'Result of the probe (success, failure, missing)' CODEC(ZSTD(1)),
    `error` String DEFAULT '' COMMENT 'Error message if probe failed' CODEC(ZSTD(1)),
    `column_indices` Array(UInt64) COMMENT 'Array of column indices probed' CODEC(ZSTD(1)),
    `blob_submitters` Array(String) COMMENT 'Array of blob submitter names for this slot (Unknown if not found)' CODEC(ZSTD(1)),
    `response_time_ms` Int32 COMMENT 'Response time in milliseconds' CODEC(ZSTD(1)),
    `username` LowCardinality(String) COMMENT 'Username extracted from client name' CODEC(ZSTD(1)),
    `node_id` LowCardinality(String) COMMENT 'Node ID extracted from client name' CODEC(ZSTD(1)),
    `classification` LowCardinality(String) COMMENT 'Classification of client (individual, corporate, internal, unclassified)' CODEC(ZSTD(1)),
    `meta_client_version` LowCardinality(String) COMMENT 'Version of the client' CODEC(ZSTD(1)),
    `meta_client_implementation` LowCardinality(String) COMMENT 'Implementation of the client' CODEC(ZSTD(1)),
    `meta_client_os` LowCardinality(String) COMMENT 'Operating system of the client' CODEC(ZSTD(1)),
    `meta_client_geo_city` LowCardinality(String) COMMENT 'City of the client' CODEC(ZSTD(1)),
    `meta_client_geo_country` LowCardinality(String) COMMENT 'Country of the client' CODEC(ZSTD(1)),
    `meta_client_geo_country_code` LowCardinality(String) COMMENT 'Country code of the client' CODEC(ZSTD(1)),
    `meta_client_geo_continent_code` LowCardinality(String) COMMENT 'Continent code of the client' CODEC(ZSTD(1)),
    `meta_client_geo_longitude` Nullable(Float64) COMMENT 'Longitude of the client' CODEC(ZSTD(1)),
    `meta_client_geo_latitude` Nullable(Float64) COMMENT 'Latitude of the client' CODEC(ZSTD(1)),
    `meta_client_geo_autonomous_system_number` Nullable(UInt32) COMMENT 'Autonomous system number of the client' CODEC(ZSTD(1)),
    `meta_client_geo_autonomous_system_organization` Nullable(String) COMMENT 'Autonomous system organization of the client' CODEC(ZSTD(1)),
    `meta_peer_implementation` LowCardinality(String) COMMENT 'Implementation of the probed peer' CODEC(ZSTD(1)),
    `meta_peer_version` LowCardinality(String) COMMENT 'Version of the probed peer' CODEC(ZSTD(1)),
    `meta_peer_platform` LowCardinality(String) COMMENT 'Platform of the probed peer' CODEC(ZSTD(1)),
    `meta_peer_geo_city` LowCardinality(String) COMMENT 'City of the probed peer' CODEC(ZSTD(1)),
    `meta_peer_geo_country` LowCardinality(String) COMMENT 'Country of the probed peer' CODEC(ZSTD(1)),
    `meta_peer_geo_country_code` LowCardinality(String) COMMENT 'Country code of the probed peer' CODEC(ZSTD(1)),
    `meta_peer_geo_continent_code` LowCardinality(String) COMMENT 'Continent code of the probed peer' CODEC(ZSTD(1)),
    `meta_peer_geo_longitude` Nullable(Float64) COMMENT 'Longitude of the probed peer' CODEC(ZSTD(1)),
    `meta_peer_geo_latitude` Nullable(Float64) COMMENT 'Latitude of the probed peer' CODEC(ZSTD(1)),
    `meta_peer_geo_autonomous_system_number` Nullable(UInt32) COMMENT 'Autonomous system number of the probed peer' CODEC(ZSTD(1)),
    `meta_peer_geo_autonomous_system_organization` Nullable(String) COMMENT 'Autonomous system organization of the probed peer' CODEC(ZSTD(1))
)
ENGINE = Distributed('{cluster}', 'mainnet', 'int_custody_probe_order_by_slot_local', cityHash64(slot_start_date_time, slot, peer_id_unique_key))
COMMENT 'Custody probe results per slot with aggregated column indices'
