tables:
  - name: beacon_api_eth_v1_beacon_committee
    database: default
    excluded_columns: []
    hourly_partitioning: true
    networks:
      mainnet:
        from: "2023-12-25"
        to: "2024-03-23"
      holesky:
        from: "2023-12-25"
        to: "2024-03-23"
      sepolia:
        from: "2023-12-24"
        to: "2024-03-23"
    quirks: >-
      Sometimes sentries may [publish different committees](https://github.com/ethpandaops/xatu/issues/288) for the same epoch.
  - name: beacon_api_eth_v1_events_attestation
    database: default
    excluded_columns: []
    hourly_partitioning: true
    networks:
      mainnet:
        from: "2024-02-20"
        to: "2024-03-23"
      holesky:
        from: "2024-02-20"
        to: "2024-03-23"
      sepolia:
        from: "2023-12-20"
        to: "2024-03-23"
  - name: beacon_api_eth_v1_events_blob_sidecar
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-12-26"
        to: "2024-03-23"
      holesky:
        from: "2023-12-20"
        to: "2024-03-23"
      sepolia:
        from: "2023-12-20"
        to: "2024-03-23"
  - name: beacon_api_eth_v1_events_block
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-12-26"
        to: "2024-03-23"
      holesky:
        from: "2023-12-20"
        to: "2024-03-23"
      sepolia:
        from: "2023-12-20"
        to: "2024-03-23"
  - name: beacon_api_eth_v1_events_chain_reorg
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-12-26"
        to: "2024-03-23"
      holesky:
        from: "2023-12-20"
        to: "2024-03-23"
      sepolia:
        from: "2023-12-20"
        to: "2024-03-23"
  - name: beacon_api_eth_v1_events_contribution_and_proof
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-12-26"
        to: "2024-03-23"
      holesky:
        from: "2023-12-20"
        to: "2024-03-23"
      sepolia:
        from: "2023-12-20"
        to: "2024-03-23"
  - name: beacon_api_eth_v1_events_finalized_checkpoint
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-12-26"
        to: "2024-03-23"
      holesky:
        from: "2023-12-20"
        to: "2024-03-23"
      sepolia:
        from: "2023-12-20"
        to: "2024-03-23"
  - name: beacon_api_eth_v1_events_head
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-12-26"
        to: "2024-03-23"
      holesky:
        from: "2023-12-20"
        to: "2024-03-23"
      sepolia:
        from: "2023-12-20"
        to: "2024-03-23"
  - name: beacon_api_eth_v1_events_voluntary_exit
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-12-26"
        to: "2024-03-23"
  - name: beacon_api_eth_v1_validator_attestation_data
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-12-26"
        to: "2024-03-23"
      holesky:
        from: "2023-12-20"
        to: "2024-03-23"
      sepolia:
        from: "2023-12-20"
        to: "2024-03-23"
  - name: beacon_api_eth_v2_beacon_block
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-12-26"
        to: "2024-03-23"
      holesky:
        from: "2023-12-20"
        to: "2024-03-23"
      sepolia:
        from: "2023-12-20"
        to: "2024-03-23"
  - name: mempool_transaction
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-03-03 03:00:00"
        to: "NOW() - INTERVAL '1 DAY'"
      holesky:
        from: "2023-12-24 02:00:00"
        to: "NOW() - INTERVAL '1 DAY'"
      sepolia:
        from: "2023-12-24 02:00:00"
        to: "NOW() - INTERVAL '1 DAY'"
    tags:
      - Execution layer
      - Transaction
      - Mempool
