datasets:
  - name: "Beacon API Event Stream"
    description: "Events derived from the Beacon API event stream"
    tables:
      prefix: beacon_api_
    availability:
      - public
      - ethpandaops-clickhouse
  - name: "Execution Layer P2P"
    description: "Events from the execution layer p2p network"
    tables:
      prefix: mempool_
    availability:
      - ethpandaops-clickhouse
      - public
  - name: "Canonical Beacon"
    description: "Events derived from the finalized beacon chain"
    tables:
      prefix: canonical_beacon_
    availability:
      - ethpandaops-clickhouse
      - public
  - name: "Consensus Layer P2P"
    description: "Events from the consensus layer p2p network"
    tables:
      prefix: libp2p_
    availability:
      - ethpandaops-clickhouse
      - public
tables:
  - name: beacon_api_eth_v1_beacon_committee
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "2023-09-05"
        to: "2024-08-24"
      holesky:
        from: "2023-12-25"
        to: "2024-08-24"
      sepolia:
        from: "2023-12-24"
        to: "2024-08-24"
    tags:
      - Consensus layer
    quirks: >-
      Sometimes sentries may [publish different committees](https://github.com/ethpandaops/xatu/issues/288) for the same epoch.
  - name: beacon_api_eth_v1_events_attestation
    database: default
    excluded_columns: []
    hourly_partitioning: true
    date_partition_column: slot_start_date_time
    networks:
      mainnet:
        from: "2023-06-05"
        to: "2024-08-24"
      holesky:
        from: "2023-09-29"
        to: "2024-08-24"
      sepolia:
        from: "2023-09-01"
        to: "2024-08-24"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v1_events_blob_sidecar
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2024-03-13"
        to: "2024-08-25"
      holesky:
        from: "2024-02-07"
        to: "2024-08-25"
      sepolia:
        from: "2024-01-30"
        to: "2024-08-25"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v1_events_block
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-02-28"
        to: "2024-08-25"
      holesky:
        from: "2023-12-24"
        to: "2024-08-25"
      sepolia:
        from: "2023-12-24"
        to: "2024-08-25"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v1_events_chain_reorg
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-03-01"
        to: "2024-08-25"
      holesky:
        from: "2024-02-05"
        to: "2024-08-25"
      sepolia:
        from: "2024-05-23"
        to: "2024-08-25"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v1_events_contribution_and_proof
    database: default
    excluded_columns: []
    date_partition_column: contribution_slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-08-31"
        to: "2024-08-25"
      holesky:
        from: "2023-12-24"
        to: "2024-08-25"
      sepolia:
        from: "2023-12-24"
        to: "2024-08-25"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v1_events_finalized_checkpoint
    database: default
    excluded_columns: []
    date_partition_column: epoch_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-04-10"
        to: "2024-08-24"
      holesky:
        from: "2023-03-26"
        to: "2024-08-24"
      sepolia:
        from: "2023-03-26"
        to: "2024-08-24"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v1_events_head
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-08-30"
        to: "2024-08-24"
      holesky:
        from: "2023-12-05"
        to: "2024-08-24"
      sepolia:
        from: "2023-12-05"
        to: "2024-08-24"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v1_events_voluntary_exit
    database: default
    excluded_columns: []
    date_partition_column: wallclock_epoch_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2020-12-01"
        to: "2024-08-24"
      holesky:
        from: "2023-10-01"
        to: "2024-08-24"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v1_validator_attestation_data
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-08-31"
        to: "2024-08-24"
      holesky:
        from: "2023-12-24"
        to: "2024-08-24"
      sepolia:
        from: "2023-12-24"
        to: "2024-08-24"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v2_beacon_block
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-11-14"
        to: "2024-08-24"
      holesky:
        from: "2023-12-24"
        to: "2024-08-24"
      sepolia:
        from: "2023-12-24"
        to: "2024-08-24"
    tags:
      - Consensus layer
  - name: mempool_transaction
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-07-22"
        to: "2024-08-24"
      holesky:
        from: "2024-01-08"
        to: "2024-08-24"
      sepolia:
        from: "2024-01-08"
        to: "2024-08-24"
    tags:
      - Execution layer
      - Transaction
      - Mempool
  - name: beacon_api_eth_v1_proposer_duty
    database: default
    excluded_columns: []
    hourly_partitioning: false
    date_partition_column: slot_start_date_time
    networks:
      mainnet:
        from: "2024-04-03"
        to: "2024-08-24"
      holesky:
        from: "2024-04-03"
        to: "2024-08-24"
      sepolia:
        from: "2024-04-03"
        to: "2024-08-24"
    tags:
      - Consensus layer
  - name: canonical_beacon_block
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2020-12-01"
        to: "2024-08-25"
      holesky:
        from: "2023-09-23"
        to: "2024-08-25"
      sepolia:
        from: "2022-06-20"
        to: "2024-08-25"
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_block_attester_slashing
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2020-12-01"
        to: "2024-08-25"
      holesky:
        from: "2023-09-23"
        to: "2024-08-25"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_block_proposer_slashing
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2020-12-01"
        to: "2024-08-25"
      holesky:
        from: "2023-09-23"
        to: "2024-08-25"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_block_bls_to_execution_change
    database: default
    date_partition_column: slot_start_date_time
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-04-12"
        to: "2024-08-25"
      holesky:
        from: "2023-09-28"
        to: "2024-08-25"
      sepolia:
        from: "2022-06-22"
        to: "2024-08-25"
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_block_execution_transaction
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2022-09-06"
        to: "2024-08-25"
      holesky:
        from: "2023-09-23"
        to: "2024-08-25"
      sepolia:
        from: "2022-06-22"
        to: "2024-08-24"
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_block_voluntary_exit
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2020-12-01"
        to: "2024-08-24"
      holesky:
        from: "2023-09-23"
        to: "2024-08-24"
      sepolia:
        from: "2022-06-22"
        to: "2024-08-24"
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_block_deposit
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2020-12-01"
        to: "2024-08-24"
      holesky:
        from: "2023-09-23"
        to: "2024-08-24"
      sepolia:
        from: "2022-06-22"
        to: "2024-08-24"
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_block_withdrawal
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-04-12"
        to: "2024-08-24"
      holesky:
        from: "2023-09-23"
        to: "2024-08-24"
      sepolia:
        from: "2023-02-28"
        to: "2024-08-24"
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_blob_sidecar
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2024-03-13"
        to: "2024-08-24"
      holesky:
        from: "2024-02-07"
        to: "2024-08-24"
      sepolia:
        from: "2024-01-30"
        to: "2024-08-24"
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_proposer_duty
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2020-12-01"
        to: "2024-08-24"
      holesky:
        from: "2023-09-23"
        to: "2024-08-24"
      sepolia:
        from: "2022-06-20"
        to: "2024-08-24"
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_elaborated_attestation
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2020-12-01"
        to: "2024-08-24"
      holesky:
        from: "2023-09-23"
        to: "2024-08-24"
      sepolia:
        from: "2022-06-22"
        to: "2024-08-24"
    tags:
      - Consensus layer
      - Finalized
  - name: libp2p_add_peer
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "null"
        to: "null"
      holesky:
        from: "null"
        to: "null"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_connected
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "null"
        to: "null"
      holesky:
        from: "null"
        to: "null"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_disconnected
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "null"
        to: "null"
      holesky:
        from: "null"
        to: "null"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_gossipsub_beacon_attestation
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "2024-05-01"
        to: "2024-08-24"
      holesky:
        from: "2024-05-01"
        to: "2024-08-24"
      sepolia:
        from: "2024-05-01"
        to: "2024-08-24"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_gossipsub_beacon_block
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2024-04-26"
        to: "2024-08-25"
      holesky:
        from: "2024-04-26"
        to: "2024-08-25"
      sepolia:
        from: "2024-04-26"
        to: "2024-08-25"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_gossipsub_blob_sidecar
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2024-06-04"
        to: "2024-08-24"
      holesky:
        from: "2024-06-04"
        to: "2024-08-24"
      sepolia:
        from: "2024-06-04"
        to: "2024-08-24"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_handle_metadata
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "null"
        to: "null"
      holesky:
        from: "null"
        to: "null"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_handle_status
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "null"
        to: "null"
      holesky:
        from: "null"
        to: "null"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_join
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "null"
        to: "null"
      holesky:
        from: "null"
        to: "null"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_peer
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "null"
        to: "null"
      holesky:
        from: "null"
        to: "null"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_recv_rpc
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "null"
        to: "null"
      holesky:
        from: "null"
        to: "null"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_remove_peer
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "null"
        to: "null"
      holesky:
        from: "null"
        to: "null"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_rpc_meta_control_graft
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "null"
        to: "null"
      holesky:
        from: "null"
        to: "null"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_rpc_meta_control_ihave
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "null"
        to: "null"
      holesky:
        from: "null"
        to: "null"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_rpc_meta_control_iwant
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "null"
        to: "null"
      holesky:
        from: "null"
        to: "null"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_rpc_meta_control_prune
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "null"
        to: "null"
      holesky:
        from: "null"
        to: "null"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_rpc_meta_message
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "null"
        to: "null"
      holesky:
        from: "null"
        to: "null"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_rpc_meta_subscription
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "null"
        to: "null"
      holesky:
        from: "null"
        to: "null"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - P2P
  - name: libp2p_send_rpc
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "null"
        to: "null"
      holesky:
        from: "null"
        to: "null"
      sepolia:
        from: "null"
        to: "null"
    tags:
      - Consensus layer
      - P2P
