tables:
  - name: beacon_api_eth_v1_events_head
    excluded_columns:
      - meta_client_id
    description: This is table1
  - name: beacon_api_eth_v1_events_block
    excluded_columns:
      - meta_client_id
    description: This is table1
