CREATE TABLE default.beacon_api_eth_v1_validator_attestation_data
(
    `updated_date_time` DateTime COMMENT 'Timestamp when the record was last updated' CODEC(DoubleDelta, ZSTD(1)),
    `event_date_time` DateTime64(3) COMMENT 'When the sentry received the event from a beacon node',
    `slot` UInt32 COMMENT 'Slot number in the beacon API validator attestation data payload',
    `slot_start_date_time` DateTime COMMENT 'The wall clock time when the slot started',
    `committee_index` LowCardinality(String) COMMENT 'The committee index in the beacon API validator attestation data payload',
    `beacon_block_root` FixedString(66) COMMENT 'The beacon block root hash in the beacon API validator attestation data payload',
    `epoch` UInt32 COMMENT 'The epoch number in the beacon API validator attestation data payload',
    `epoch_start_date_time` DateTime COMMENT 'The wall clock time when the epoch started',
    `source_epoch` UInt32 COMMENT 'The source epoch number in the beacon API validator attestation data payload',
    `source_epoch_start_date_time` DateTime COMMENT 'The wall clock time when the source epoch started',
    `source_root` FixedString(66) COMMENT 'The source beacon block root hash in the beacon API validator attestation data payload',
    `target_epoch` UInt32 COMMENT 'The target epoch number in the beacon API validator attestation data payload',
    `target_epoch_start_date_time` DateTime COMMENT 'The wall clock time when the target epoch started',
    `target_root` FixedString(66) COMMENT 'The target beacon block root hash in the beacon API validator attestation data payload',
    `request_date_time` DateTime COMMENT 'When the request was sent to the beacon node',
    `request_duration` UInt32 COMMENT 'Time in milliseconds for the Beacon API request to complete',
    `request_slot_start_diff` UInt32 COMMENT 'Time in milliseconds since the start of the slot when the request was made',
    `meta_client_name` LowCardinality(String) COMMENT 'Name of the Sentry client that collected the data. The table contains data from multiple Sentry clients',
    `meta_client_id` String COMMENT 'Unique Session ID of the client that generated the event. This changes every time the client is restarted.',
    `meta_client_version` LowCardinality(String) COMMENT 'Version of the client that generated the event',
    `meta_client_implementation` LowCardinality(String) COMMENT 'Implementation of the client that generated the event',
    `meta_client_os` LowCardinality(String) COMMENT 'Operating system of the client that generated the event',
    `meta_client_ip` Nullable(IPv6) COMMENT 'IP address of the client that generated the event',
    `meta_client_geo_city` LowCardinality(String) COMMENT 'City of the client that generated the event',
    `meta_client_geo_country` LowCardinality(String) COMMENT 'Country of the client that generated the event',
    `meta_client_geo_country_code` LowCardinality(String) COMMENT 'Country code of the client that generated the event',
    `meta_client_geo_continent_code` LowCardinality(String) COMMENT 'Continent code of the client that generated the event',
    `meta_client_geo_longitude` Nullable(Float64) COMMENT 'Longitude of the client that generated the event',
    `meta_client_geo_latitude` Nullable(Float64) COMMENT 'Latitude of the client that generated the event',
    `meta_client_geo_autonomous_system_number` Nullable(UInt32) COMMENT 'Autonomous system number of the client that generated the event',
    `meta_client_geo_autonomous_system_organization` Nullable(String) COMMENT 'Autonomous system organization of the client that generated the event',
    `meta_network_id` Int32 COMMENT 'Ethereum network ID',
    `meta_network_name` LowCardinality(String) COMMENT 'Ethereum network name',
    `meta_consensus_version` LowCardinality(String) COMMENT 'Ethereum consensus client version that generated the event',
    `meta_consensus_version_major` LowCardinality(String) COMMENT 'Ethereum consensus client major version that generated the event',
    `meta_consensus_version_minor` LowCardinality(String) COMMENT 'Ethereum consensus client minor version that generated the event',
    `meta_consensus_version_patch` LowCardinality(String) COMMENT 'Ethereum consensus client patch version that generated the event',
    `meta_consensus_implementation` LowCardinality(String) COMMENT 'Ethereum consensus client implementation that generated the event',
    `meta_labels` Map(String, String) COMMENT 'Labels associated with the event'
)
ENGINE = Distributed('{cluster}', 'default', 'beacon_api_eth_v1_validator_attestation_data_local', cityHash64(slot_start_date_time, meta_network_name, meta_client_name, committee_index, beacon_block_root, source_root, target_root))
COMMENT 'Xatu Sentry calls the Beacon API `/eth/v1/validator/attestation_data` endpoint to fetch attestation data. Each row contains attestation data with request timing metrics. Partition: monthly by `slot_start_date_time`.'
