CREATE TABLE default.libp2p_synthetic_heartbeat
(
    `updated_date_time` DateTime CODEC(DoubleDelta, ZSTD(1)),
    `event_date_time` DateTime64(3) CODEC(DoubleDelta, ZSTD(1)),
    `remote_peer_id_unique_key` Int64,
    `remote_maddrs` String CODEC(ZSTD(1)),
    `latency_ms` Nullable(Int64) CODEC(ZSTD(1)),
    `direction` LowCardinality(String),
    `protocols` Array(String) CODEC(ZSTD(1)),
    `connection_age_ms` Nullable(Int64) CODEC(ZSTD(1)),
    `remote_agent_implementation` LowCardinality(String),
    `remote_agent_version` LowCardinality(String),
    `remote_agent_version_major` LowCardinality(String),
    `remote_agent_version_minor` LowCardinality(String),
    `remote_agent_version_patch` LowCardinality(String),
    `remote_agent_platform` LowCardinality(String),
    `remote_ip` Nullable(IPv6) CODEC(ZSTD(1)),
    `remote_port` Nullable(UInt16) CODEC(ZSTD(1)),
    `remote_geo_city` LowCardinality(String) CODEC(ZSTD(1)),
    `remote_geo_country` LowCardinality(String) CODEC(ZSTD(1)),
    `remote_geo_country_code` LowCardinality(String) CODEC(ZSTD(1)),
    `remote_geo_continent_code` LowCardinality(String) CODEC(ZSTD(1)),
    `remote_geo_longitude` Nullable(Float64) CODEC(ZSTD(1)),
    `remote_geo_latitude` Nullable(Float64) CODEC(ZSTD(1)),
    `remote_geo_autonomous_system_number` Nullable(UInt32) CODEC(ZSTD(1)),
    `remote_geo_autonomous_system_organization` Nullable(String) CODEC(ZSTD(1)),
    `meta_client_name` LowCardinality(String) COMMENT 'Name of the client that collected the data. The table contains data from multiple clients',
    `meta_client_id` String CODEC(ZSTD(1)),
    `meta_client_version` LowCardinality(String),
    `meta_client_implementation` LowCardinality(String),
    `meta_client_os` LowCardinality(String),
    `meta_client_ip` Nullable(IPv6) CODEC(ZSTD(1)),
    `meta_client_geo_city` LowCardinality(String) CODEC(ZSTD(1)),
    `meta_client_geo_country` LowCardinality(String) CODEC(ZSTD(1)),
    `meta_client_geo_country_code` LowCardinality(String) CODEC(ZSTD(1)),
    `meta_client_geo_continent_code` LowCardinality(String) CODEC(ZSTD(1)),
    `meta_client_geo_longitude` Nullable(Float64) CODEC(ZSTD(1)),
    `meta_client_geo_latitude` Nullable(Float64) CODEC(ZSTD(1)),
    `meta_client_geo_autonomous_system_number` Nullable(UInt32) CODEC(ZSTD(1)),
    `meta_client_geo_autonomous_system_organization` Nullable(String) CODEC(ZSTD(1)),
    `meta_network_id` Int32 CODEC(DoubleDelta, ZSTD(1)),
    `meta_network_name` LowCardinality(String)
)
ENGINE = Distributed('{cluster}', 'default', 'libp2p_synthetic_heartbeat_local', cityHash64(event_date_time, meta_network_name, meta_client_name, remote_peer_id_unique_key, updated_date_time))
COMMENT 'Contains periodic heartbeat snapshots of libp2p peer state. Collected from deep instrumentation within forked consensus layer clients. Each row contains mesh/peer counts and topic subscriptions at that moment. Partition: monthly by `event_date_time`.'
