CREATE TABLE default.libp2p_identify
(
    `updated_date_time` DateTime COMMENT 'Timestamp when the record was last updated' CODEC(DoubleDelta, ZSTD(1)),
    `event_date_time` DateTime64(3) COMMENT 'Timestamp of the event' CODEC(DoubleDelta, ZSTD(1)),
    `remote_peer_id_unique_key` Int64 COMMENT 'Unique key associated with the identifier of the remote peer' CODEC(ZSTD(1)),
    `success` Bool COMMENT 'Whether the identify request was successful' CODEC(ZSTD(1)),
    `error` Nullable(String) COMMENT 'Error message if the identify request failed' CODEC(ZSTD(1)),
    `remote_protocol` LowCardinality(String) COMMENT 'Protocol of the remote peer',
    `remote_transport_protocol` LowCardinality(String) COMMENT 'Transport protocol of the remote peer',
    `remote_port` UInt16 COMMENT 'Port of the remote peer' CODEC(ZSTD(1)),
    `remote_ip` Nullable(IPv6) COMMENT 'IP address of the remote peer that generated the event' CODEC(ZSTD(1)),
    `remote_geo_city` LowCardinality(String) COMMENT 'City of the remote peer that generated the event' CODEC(ZSTD(1)),
    `remote_geo_country` LowCardinality(String) COMMENT 'Country of the remote peer that generated the event' CODEC(ZSTD(1)),
    `remote_geo_country_code` LowCardinality(String) COMMENT 'Country code of the remote peer that generated the event' CODEC(ZSTD(1)),
    `remote_geo_continent_code` LowCardinality(String) COMMENT 'Continent code of the remote peer that generated the event' CODEC(ZSTD(1)),
    `remote_geo_longitude` Nullable(Float64) COMMENT 'Longitude of the remote peer that generated the event' CODEC(ZSTD(1)),
    `remote_geo_latitude` Nullable(Float64) COMMENT 'Latitude of the remote peer that generated the event' CODEC(ZSTD(1)),
    `remote_geo_autonomous_system_number` Nullable(UInt32) COMMENT 'Autonomous system number of the remote peer that generated the event' CODEC(ZSTD(1)),
    `remote_geo_autonomous_system_organization` Nullable(String) COMMENT 'Autonomous system organization of the remote peer that generated the event' CODEC(ZSTD(1)),
    `remote_agent_implementation` LowCardinality(String) COMMENT 'Implementation of the remote peer',
    `remote_agent_version` LowCardinality(String) COMMENT 'Version of the remote peer',
    `remote_agent_version_major` LowCardinality(String) COMMENT 'Major version of the remote peer',
    `remote_agent_version_minor` LowCardinality(String) COMMENT 'Minor version of the remote peer',
    `remote_agent_version_patch` LowCardinality(String) COMMENT 'Patch version of the remote peer',
    `remote_agent_platform` LowCardinality(String) COMMENT 'Platform of the remote peer',
    `protocol_version` LowCardinality(String) COMMENT 'Protocol version reported by the remote peer',
    `protocols` Array(String) COMMENT 'List of protocols supported by the remote peer' CODEC(ZSTD(1)),
    `listen_addrs` Array(String) COMMENT 'List of multiaddresses the remote peer is listening on' CODEC(ZSTD(1)),
    `observed_addr` String COMMENT 'Multiaddress the remote peer observed for the local peer' CODEC(ZSTD(1)),
    `transport` LowCardinality(String) COMMENT 'Transport protocol used for the connection',
    `security` LowCardinality(String) COMMENT 'Security protocol used for the connection',
    `muxer` LowCardinality(String) COMMENT 'Stream multiplexer used for the connection',
    `direction` LowCardinality(String) COMMENT 'Connection direction',
    `remote_multiaddr` String COMMENT 'Full multiaddress of the remote peer' CODEC(ZSTD(1)),
    `meta_client_name` LowCardinality(String) COMMENT 'Name of the client that collected the data. The table contains data from multiple clients',
    `meta_client_id` String COMMENT 'Unique Session ID of the client that generated the event. This changes every time the client is restarted.' CODEC(ZSTD(1)),
    `meta_client_version` LowCardinality(String) COMMENT 'Version of the client that generated the event',
    `meta_client_implementation` LowCardinality(String) COMMENT 'Implementation of the client that generated the event',
    `meta_client_os` LowCardinality(String) COMMENT 'Operating system of the client that generated the event',
    `meta_client_ip` Nullable(IPv6) COMMENT 'IP address of the client that generated the event' CODEC(ZSTD(1)),
    `meta_client_geo_city` LowCardinality(String) COMMENT 'City of the client that generated the event' CODEC(ZSTD(1)),
    `meta_client_geo_country` LowCardinality(String) COMMENT 'Country of the client that generated the event' CODEC(ZSTD(1)),
    `meta_client_geo_country_code` LowCardinality(String) COMMENT 'Country code of the client that generated the event' CODEC(ZSTD(1)),
    `meta_client_geo_continent_code` LowCardinality(String) COMMENT 'Continent code of the client that generated the event' CODEC(ZSTD(1)),
    `meta_client_geo_longitude` Nullable(Float64) COMMENT 'Longitude of the client that generated the event' CODEC(ZSTD(1)),
    `meta_client_geo_latitude` Nullable(Float64) COMMENT 'Latitude of the client that generated the event' CODEC(ZSTD(1)),
    `meta_client_geo_autonomous_system_number` Nullable(UInt32) COMMENT 'Autonomous system number of the client that generated the event' CODEC(ZSTD(1)),
    `meta_client_geo_autonomous_system_organization` Nullable(String) COMMENT 'Autonomous system organization of the client that generated the event' CODEC(ZSTD(1)),
    `meta_network_id` Int32 COMMENT 'Ethereum network ID' CODEC(DoubleDelta, ZSTD(1)),
    `meta_network_name` LowCardinality(String) COMMENT 'Ethereum network name'
)
ENGINE = Distributed('{cluster}', 'default', 'libp2p_identify_local', cityHash64(event_date_time, meta_network_name, meta_client_name, remote_peer_id_unique_key, direction))
COMMENT 'Contains libp2p identify events with peer identification data including agent version, protocols, and connection metadata. Collected from deep instrumentation within forked consensus layer clients. Each row includes remote peer agent info, supported protocols, listen addresses, and geolocation. Partition: monthly by `event_date_time`.'
