name: Update config

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-availability:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Run update-availability script for all datasets
        run: |
            echo "Running update-availability script for all datasets"
            ./update-availability.sh "Beacon API Event Stream"
            ./update-availability.sh "Execution Layer P2P"
            ./update-availability.sh "Canonical Beacon"
            ./update-availability.sh "Consensus Layer P2P"
      - name: Commit changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git commit -m "Update data availability" || echo "No changes to commit"
          git push
      - name: Trigger deploy hook
        run: |
          curl -X POST "${{ secrets.HOMEPAGE_HOOK_URL }}"
